# Generated by Django 5.2.1 on 2025-06-03 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва роботи')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image_preview', models.ImageField(upload_to='art_previews/', verbose_name="Зображення-прев'ю")),
                ('image_full', models.ImageField(upload_to='art_full/', verbose_name='Повне зображення')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата додавання')),
                ('instagram_link', models.URLField(blank=True, max_length=250, null=True, verbose_name='Посилання на Instagram')),
            ],
            options={
                'verbose_name': 'Робота (Арт)',
                'verbose_name_plural': 'Роботи (Арти)',
                'ordering': ['-created_at'],
            },
        ),
    ]
