# Generated by Django 5.2.1 on 2025-06-05 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_api', '0002_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва колекції')),
                ('description', models.TextField(blank=True, verbose_name='Опис колекції')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='collection_previews/', verbose_name="Зображення-прев'ю колекції")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Колекція одягу',
                'verbose_name_plural': 'Колекції одягу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, verbose_name='Опис предмету')),
                ('imvu_link', models.URLField(max_length=250, verbose_name='Посилання на IMVU')),
                ('item_preview_image', models.ImageField(upload_to='clothing_items/', verbose_name='Зображення предмету')),
                ('gender', models.CharField(choices=[('MALE', 'Чоловічий'), ('FEMALE', 'Жіночий'), ('UNISEX', 'Унісекс')], max_length=10, verbose_name='Стать')),
                ('category', models.CharField(choices=[('TOP', 'Верх (Top)'), ('BOTTOM', 'Низ (Bottom)'), ('SHOES', 'Взуття (Shoes)'), ('HAIR', 'Волосся (Hair)'), ('ACCESSORIES', 'Аксесуари (Accessories)'), ('FULL_OUTFIT', 'Повний образ (Full Outfit)')], max_length=20, verbose_name='Тип одягу')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата додавання')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='likes_api.collection', verbose_name='Належить до колекції')),
            ],
            options={
                'verbose_name': 'Предмет одягу',
                'verbose_name_plural': 'Предмети одягу',
                'ordering': ['-added_at'],
            },
        ),
    ]
