# Generated by Django 5.2.1 on 2025-06-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_api', '0003_collection_clothingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_galleries/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name="Підпис до зображення (необов'язково)")),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='likes_api.collection', verbose_name='Колекція')),
            ],
            options={
                'verbose_name': 'Зображення колекції',
                'verbose_name_plural': 'Зображення колекцій',
            },
        ),
    ]
